# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Docker
    displayName: Build And Push Docker Image 
    jobs:

    - job: Build 
      displayName: Build and Push Docker Image
      pool:
        vmImage: ubuntu-latest
      variables: 
      - group: AzureKeyVaultVars
      steps:
      - bash: |
          echo 'Building the docker image on azure pipeline'
          echo '##This is the pipeline workspace $(Pipeline.Workspace)'
          echo '##This is the environment variable for Azure_Key_Vault_Name $(Azure_Key_Vault_Name)'
          echo 'current tag value $(tag)'
          ls
          pwd
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub(luisenalvar)'
      - script: |
          cd ./SecureAPI
          docker image build --file **/Dockerfile --tag azsecureapi --build-arg KEYVAULTNAME=$(Azure_Key_Vault_Name) . 
          docker image tag azsecureapi luisenalvar/azsecureapi
          docker push luisenalvar/azsecureapi

  # - stage: Deploy  
  #   displayName: 'Azure Provision of Resources ...'
  #   dependsOn: Build
  #   jobs:
  #   - job: AppDeployment 
  #     displayName: 'Create a App Container Instance'
  #     pool:
  #       vmImage: ubuntu-latest
  #     variables:
  #     - group: TerraformServicePrincipalEnvVars
  #     - group: Azure_Key_Vault_Name
  #     steps:
  #     - script: |
  #         set -e
  #         terraform init -input=false
  #         terraform apply -input=false -auto-approve
  #       name: Terraform 
  #       displayName: 'Running Terraform  ...'
  #       env:
  #         ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  #         ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  #         ARM_TENANT_ID: $(ARM_TENANT_ID)
  #         ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  #         TF_VAR_imagebuild_id: $(tag)
