# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Docker Image 
    jobs:
    - job: Build 
      displayName: Build Docker Image
      pool:
        vmImage: ubuntu-latest
      steps:
      - bash: |
          echo $(date + %Y)
          echo $(Pipeline.Workspace)
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub(luisenalvar)'
          repository: 'luisenalvar/azsecureapi'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          arguments: '--build-arg KEYVAULTNAME=$(Azure_Key_Vault_Name)'
          tags: |
            $(tag)

